
AN ERROR HAS OCCURRED [assertion failed]

CALLSTACK
*FUNCTION [__main__()] testData/static_analyzer/w248_assert.nut line [11]

LOCALS
[c] NULL
[o] NULL
[foo] CLOSURE
[vargv] ARRAY
[this] NULL
