
AN ERROR HAS OCCURRED [the index 'value' does not exist]

CALLSTACK
*FUNCTION [__main__()] testData/static_analyzer/w248_evaled.nut:6

LOCALS
[foo] CLOSURE=FN:foo
[t] TABLE={}
[vargv] ARRAY=[]
[this] NULL
