
AN ERROR HAS OCCURRED [the index 'value' does not exist]

CALLSTACK
*FUNCTION [__main__()] testData/static_analyzer/w248_eq_get.nut:5

LOCALS
[o] TABLE={}
[foo] CLOSURE=FN:foo
[vargv] ARRAY=[]
[this] NULL
