
AN ERROR HAS OCCURRED [the index 'foo' does not exist]

CALLSTACK
*FUNCTION [__main__()] testData/static_analyser/w238_idname.nut line [3]

LOCALS
[state] TABLE
[vargv] ARRAY
[this] TABLE
